# Generated by Django 5.2.4 on 2026-03-19 02:23

import api.mixins
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
        #('social_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pending_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profile_imagen', models.ImageField(blank=True, null=True, storage=api.mixins.ProfileCloudinaryStorage(), upload_to='profile_images/')),
                ('banner_imagen', models.ImageField(blank=True, null=True, storage=api.mixins.BannerCloudinaryStorage(), upload_to='banner_images/')),
                ('ubicacion_coordenadas', models.JSONField(blank=True, default=None, null=True)),
                ('biometric', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad_coordenadas', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('negocio', models.JSONField(blank=True, default=None, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-id'],
            },
            bases=(api.mixins.AutoCleanMongoMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('description', models.TextField()),
                ('imagen_urls', models.JSONField(default=list)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moneda', models.CharField(blank=True, choices=[('ARS', 'Peso argentino'), ('BOB', 'Boliviano'), ('BRL', 'Real brasileño'), ('CLP', 'Peso chileno'), ('COP', 'Peso colombiano'), ('CRC', 'Colón costarricense'), ('CUP', 'Peso cubano'), ('DOP', 'Peso dominicano'), ('USD', 'Dólar estadounidense'), ('EUR', 'Euro'), ('GTQ', 'Quetzal guatemalteco'), ('GYD', 'Dólar guyanés'), ('HTG', 'Gourde haitiano'), ('HNL', 'Lempira hondureño'), ('MXN', 'Peso mexicano'), ('NIO', 'Córdoba nicaragüense'), ('PAB', 'Balboa panameño'), ('PYG', 'Guaraní paraguayo'), ('PEN', 'Sol peruano'), ('SRD', 'Dólar surinamés'), ('TTD', 'Dólar de Trinidad y Tobago'), ('UYU', 'Peso uruguayo'), ('VES', 'Bolívar venezolano')], max_length=3, null=True)),
                ('negocio', models.ForeignKey(limit_choices_to={'negocio__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='negocio_servicio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['-id'],
            },
            bases=(api.mixins.AutoCleanMongoMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El rating mínimo es 1.'), django.core.validators.MaxValueValidator(5, message='El rating máximo es 5.')])),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(limit_choices_to={'negocio__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='comments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-date'],
                'unique_together': {('negocio', 'cliente')},
            },
        ),
    ]
