# Generated by Django 5.2.4 on 2026-04-01 02:52

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('social_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialAuthProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Usuario OAuth2',
                'verbose_name_plural': 'Usuarios OAuth2',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('social_django.usersocialauth',),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_texto', models.TextField(db_column='content')),
                ('hora_mensaje', models.DateTimeField(auto_now_add=True)),
                ('visto', models.BooleanField(db_column='read', default=False)),
                ('emisor', models.ForeignKey(blank=True, db_column='sender', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje de chat',
                'verbose_name_plural': 'Mensajes de chat',
                'ordering': ['hora_mensaje'],
            },
        ),
    ]
