# Generated by Django 5.2.4 on 2026-04-26 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersocialauthproxy_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['hora_mensaje'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chat'},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='emisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='mensaje_texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
