"""
Django settings for vuzco project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os 
import django_mongodb_backend

from decouple import config, Csv
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = False
#ALLOWED_HOSTS = ['apinegocio.vercel.app']

DEBUG = config('DEBUG', cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'daphne',
    'vuzco.apps.MongoAdminConfig',
    'vuzco.apps.MongoAuthConfig',
    'vuzco.apps.MongoContentTypesConfig',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'api.apps.SocialDjangoConfig',
    'cloudinary', #storage
    'cloudinary_storage', #storage
    'djoser', # envio de emails
    'rest_framework', # api
    'rest_framework_simplejwt', # api con jwt 
    'drf_spectacular', #tiene varias funciones una de ellas es la documentacion de swagger
    'corsheaders', # permite que urls pueden consumir la api
    'pwa', #pwa
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe ir antes de cualquier middleware que maneje solicitudes
    'social_django.middleware.SocialAuthExceptionMiddleware', #middleware modificado para que sea compatible con mongo
    #'vuzco.middleware.BlockPostmanMiddleware',
    #'vuzco.middleware.CustomHeaderMiddleware', 
    'vuzco.middleware.DisableAdminLogMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', #storage
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vuzco.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect'
            ],
        },
    },
]



JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Vuzco",


    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Vuzco",

    

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "images/favicon.png",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": None,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,
    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": None,

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": None,

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": None,

    # Welcome text on the login screen
    "welcome_sign": "Bienvenido. Por favor ingrese sus datos",

    # Copyright on the footer
    "copyright": "Vuzco",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string 
  

    # Field name on user model that contains avatar ImageField/URLField/Charfield or a callable that receives the user
    "user_avatar": None,

    ############
    # Top Menu #
    ############

    
    #############
    # User Menu #########@eqweqw@@@@@@@@
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        # Usar URL relativa para que funcione en cualquier dominio/despliegue
        {"name": "Docs", "url": "/api/docs/", "new_window": False},
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "books": [{
            "name": "Make Messages", 
            "url": "make_messages", 
            "icon": "fas fa-comments",
            "permissions": ["books.view_book"]
        }]
    },

    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    
    "custom_css": "css/custom_login.css",
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    
}

JAZZMIN_UI_TWEAKS = {
    
    "theme": "pulse",
}



WSGI_APPLICATION = 'vuzco.wsgi.application'
ASGI_APPLICATION = 'vuzco.asgi.application'

REDIS_URL = config('REDIS_URL', default='redis://redis_db:6379')

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL,
    }
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {"default": django_mongodb_backend.parse_uri(config('MONGODB_URI'))}

# Database routers
# https://docs.djangoproject.com/en/dev/ref/settings/#database-routers
DATABASE_ROUTERS = ["django_mongodb_backend.routers.MongoRouter", "vuzco.routers.PermissionRouter"]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
#Codigo para definir el formato de numeros. Ejemplo 100.000,00 (formato europeo/latinoamericano) o 100,000.00 (formato anglosajón),
USE_L10N = True  # Asegúrate que esté en True
USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/build')  # Archivos para produccion

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

SIGHTENGINE_API_USER = config('SIGHTENGINE_API_USER')

SIGHTENGINE_API_SECRET = config('SIGHTENGINE_API_SECRET')

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_PROFILE_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_PROFILE_API_KEY'),
    'API_SECRET': config('CLOUDINARY_PROFILE_API_SECRET')
}

# Configuración secundaria (para servicios)
SERVICIOS_CLOUDINARY = {
    'CLOUD_NAME': config('CLOUDINARY_SERVICES_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_SERVICES_API_KEY'),
    'API_SECRET': config('CLOUDINARY_SERVICES_API_SECRET')
}

# Configuración secundaria (para servicios)
CLOUDINARY_BANNER = {
    'CLOUD_NAME': config('CLOUDINARY_BANNER_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_BANNER_API_KEY'),
    'API_SECRET': config('CLOUDINARY_BANNER_API_SECRET')
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'

MIGRATION_MODULES = {
    'admin': 'mongo_migrations.admin',
    'auth': 'mongo_migrations.auth',
    'contenttypes': 'mongo_migrations.contenttypes',
    'social_django': 'mongo_migrations.social_django', #Creada manualmente
}

#Aqui indico y permito que URL pueda accedar a la api
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv())

# ✅ Permitir redirecciones a protocolos personalizados (vuzco://)
ALLOWED_REDIRECT_PROTOCOLS = ['http', 'https', 'vuzco']

# ✅ Para versiones más recientes de Django, también necesitas:
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'vuzco-Secret'  # Header personalizado
]


CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

# Validacion para que solo los urls del CORS consuman la api en produccion
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

SECURE_API_HEADER = 'vuzco-Secret'  
SECURE_API_VALUE = config('API_VALUE')  # DEBE SER EL MISMO QUE EN IONIC

AUTH_USER_MODEL = 'api.User'


REST_FRAMEWORK = {
    
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    #DRF JWT
       'DEFAULT_AUTHENTICATION_CLASSES': (
           'rest_framework_simplejwt.authentication.JWTAuthentication',
       ),

    #PERMISOS
       'DEFAULT_PERMISSION_CLASS': ('rest_framework.permissions.IsAuthenticated',),
    #DRF SPECTACULAR
       'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
  
   }

SIMPLE_JWT = {
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('JWT',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    #Tiempo de expiracion del TOKEN

    #PARA DESARROLLO ESTA CONFIGURACION

    # Tiempo de vida del token de acceso (default: 5 minutos)
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # 1 hora
    ## Tiempo de vida del token de refresco (default: 1 día)
    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),  # 1 semana

    #PARA PRODUCCION ESTA CONFIGURACION
    #'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365*100),  # 100 años (prácticamente nunca)

    #'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365*100),  # 100 años (prácticamente nunca)
    # Tiempo de vida del token de refresco cuando se usa para renovar (default: None)
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    # Permite renovar el refresh token cada vez que se usa
    'ROTATE_REFRESH_TOKENS': True,
    
    # Invalida los refresh tokens después de usarlos
    'BLACKLIST_AFTER_ROTATION': True,
    
    # Actualiza la última hora de inicio de sesión del usuario
    'UPDATE_LAST_LOGIN': True,
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True

DEFAULT_FROM_EMAIL = 'Vuzco App <ebirutech@gmail.com>' 
DOMAIN = 'vuzco.vercel.app'
SITE_NAME = 'Vuzco' 
PROTOCOL = 'https'

AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend'
)

DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE': True,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'SEND_CONFIRMATION_EMAIL': True,
    'SEND_ACTIVATION_EMAIL': True,
    'SET_USERNAME_RETYPE': True,
    'SET_PASSWORD_RETYPE': True,
    # Aquí Djoser construirá la URL por mi, por eso no debo poner el dominio
    'PASSWORD_RESET_CONFIRM_URL': 'password/confirm/{uid}/{token}/',
    'USERNAME_RESET_CONFIRM_URL': 'email/confirm/{uid}/{token}/',
    'ACTIVATION_URL': 'activate/{uid}/{token}/',
    'SOCIAL_AUTH_TOKEN_STRATEGY': 'djoser.social.token.jwt.TokenStrategy',
    'SOCIAL_AUTH_ALLOWED_REDIRECT_URIS': 
    [
        #Aqui esta mandando el backend a las urls del frontend
        'https://vuzco.vercel.app/google', 
        'https://vuzco.vercel.app/facebook'
    ],
    'SERIALIZERS': {
        'user_create': 'api.serializers.UserCreateSerializer',
        'user': 'api.serializers.UserCreateSerializer',
        'current_user': 'api.serializers.UserCreateSerializer',
        'user_delete': 'djoser.serializers.UserDeleteSerializer',
    },
    'EMAIL': {
        'activation': 'api.custom_email.CreateUser', #Confirmacion de correo
        'activation_confirm': 'api.custom_email.CustomActivationConfirmEmail', #Mensaje de confirmacion exitosa y activacion de cuenta
        'password_reset': 'api.custom_email.CustomPasswordResetEmail', #solicitud para recuperar password olvidada
        'password_changed_confirmation': 'api.custom_email.CustomPasswordConfirmEmail', #enlace que abro para nueva password
        'username_reset': 'api.custom_email.CustomUsernameResetEmail', #solicitud para recuperar email olvidado
        'email_changed_confirmation': 'api.custom_email.CustomActivationNewEmail',  #solicitud para activar nuevo email 
    },
}

LOGIN_REDIRECT_URL = 'https://vuzco.vercel.app/'
#LOGOUT_REDIRECT_URL = 'https://vuzco.vercel.app/'


SOCIAL_AUTH_UNIQUE_USERNAME = True
SOCIAL_AUTH_USERNAME_IS_FULL_EMAIL = True
SOCIAL_AUTH_CLEAN_USERNAME = True
SOCIAL_AUTH_SLUGIFY_USERNAME = True

# Prevenir duplicados
SOCIAL_AUTH_GOOGLE_OAUTH2_IGNORE_DUPLICATE_EMAILS = False

# Forzar siempre selección de cuenta
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'prompt': 'select_account',
    'access_type': 'offline',
    'include_granted_scopes': 'true'
}


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY') #cliente id
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['https://www.googleapis.com/auth/userinfo.email', 'https://www.googleapis.com/auth/userinfo.profile', 'openid']
SOCIAL_AUTH_GOOGLE_OAUTH2_EXTRA_DATA = ['first_name', 'last_name']

SOCIAL_AUTH_PROCESS_EXCEPTIONS = True
SOCIAL_AUTH_RAISE_EXCEPTIONS = False
SOCIAL_AUTH_EXCEPTION_HANDLER = 'api.pipeline.social_auth_exception_handler'

SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    
    # Manejar email duplicado TEMPRANO en el proceso
    'api.pipeline.handle_duplicate_email',
    
    'social_core.pipeline.social_auth.social_user',

    # Generar username único
    'api.pipeline.get_username',
    
    # Prevenir sobrescritura
    'api.pipeline.prevent_user_overwrite',
    
    # Nuestra asociación personalizada
    'api.pipeline.custom_associate_user',
    
    # Crear usuario con nuestro método personalizado
    'api.pipeline.create_user',
    
    # Asociación normal (como respaldo)
    'social_core.pipeline.social_auth.associate_user',
    
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    
    # Verificación final
    'api.pipeline.ensure_unique_association',
    'api.pipeline.save_profile_picture',
    'api.pipeline.redirect_with_token',
)

SOCIAL_AUTH_FACEBOOK_KEY = '[YOUR FACEBOOK API KEY]'
SOCIAL_AUTH_FACEBOOK_SECRET = '[YOUR FACEBOOK API SECRET]'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'email, first_name, last_name'
}

#Configuracion de Swagger
SPECTACULAR_SETTINGS = {
    'TITLE': 'Vuzco',
    'DESCRIPTION': 'API REST utilizada como Backend para la Red Social Vuzco. Desarrollada en Django Rest, MongoDB, autenticacion mediante JWT, envio de correos, autenticacion con Google, almacenamiento de Imagenes con Cloudinary y despliegue en Vercel',
    'VERSION': '1.0.0',
    'CONTACT': {
        'name': 'Vuzco',
        'email': 'jesusmedina0921@gmail.com',
        'url': 'https://vuzco.vercel.app',
    },
    #Orden de los tags en Swagger
    'TAGS': [
        {'name': 'Login', 'description': 'Operaciones de autenticación'},
        {'name': 'Token', 'description': 'Operaciones relacionadas para reiniciar JWT'},
        {'name': 'auth', 'description': 'Operaciones relacionadas con la recuperacion de email/password, autenticacion de cuentas etc...'},
        {'name': 'Clientes', 'description': 'Operaciones relacionadas con los clientes'},
        {'name': 'Negocios', 'description': 'Operaciones relacionadas con los negocios'},
        {'name': 'Comentarios', 'description': 'Operaciones relacionadas con los comentarios de los Negocios'},
        {'name': 'Servicios', 'description': 'Operaciones relacionadas con los servicios publicados por las negocios'},
        {'name': 'Chat', 'description': 'Operaciones relacionadas con los mensajes de chat'},
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
}


PWA_APP_NAME = 'Vuzco'
PWA_APP_DESCRIPTION = "Vuzco"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = "#1c4216"
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {'src': '/static/images/icons/icon-72x72.png', 'sizes': '72x72'},
    {'src': '/static/images/icons/icon-96x96.png', 'sizes': '96x96'},
    {'src': '/static/images/icons/icon-128x128.png', 'sizes': '128x128'},
    {'src': '/static/images/icons/icon-144x144.png', 'sizes': '144x144'},
    {'src': '/static/images/icons/icon-152x152.png', 'sizes': '152x152'},
    {'src': '/static/images/icons/icon-192x192.png', 'sizes': '192x192'},
    {'src': '/static/images/icons/icon-384x384.png', 'sizes': '384x384'},
    {'src': '/static/images/icons/icon-512x512.png', 'sizes': '512x512'},
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'es'