############EL ARCHIVO ROUTING ES PARA LA LIBRERIA CHANNELS

from django.urls import path
from .consumers import ChatConsumer

websocket_urlpatterns = [
    path('ws/chat/<receptor_id>/', ChatConsumer.as_asgi()),
    #ESE NOMBRE DE RECEPTOR_ID ES EL QUE SE USA EN EL CONSUMER 
    # PARA OBTENER EL ID DEL RECEPTOR Y ASI SABER A QUIEN LE LLEGA EL MENSAJE
    # Y ADEMAS ES PORQUE ESTA REGISTRADO EN EL URLS.PY CON ESA RUTA, ASI QUE DEBE COINCIDIR
    # Y TAMBIEN ESTA EN EL MODELO CHATMESSAGE COMO RECEPTOR, ASI QUE DEBE COINCIDIR CON EL NOMBRE DEL PARAMETRO EN LA RUTA
]